default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web_scraper_development
  username: postgres
  password: root
  host: localhost
  port: 5432

production:
  <<: *default
  database: web_scraper_production
  username: postgres
  password: root
  host: 139.59.20.229
 

